title: GAMESpy
description: Here i publish different games using python.
template:
  repo: gamespy-template
  name: gamespy
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
